name: Bug report
description: Report a bug or unexpected behaviour
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill in as much detail as you can.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: input
    id: consumer-version
    attributes:
      label: Consumer SDK version
      description: Run `npm ls @littlebearapps/platform-consumer-sdk`
      placeholder: "1.1.1"
    validations:
      required: true

  - type: input
    id: admin-version
    attributes:
      label: Admin SDK version (if applicable)
      description: Run `npm ls @littlebearapps/platform-admin-sdk`
      placeholder: "1.2.0"

  - type: dropdown
    id: package
    attributes:
      label: Affected package
      description: Which package does this affect?
      options:
        - Consumer SDK
        - Admin SDK
        - Both
        - Documentation
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug
      placeholder: |
        1. Wrap handler with `withFeatureBudget(env, 'myapp:api:main', { ctx })`
        2. Deploy with `wrangler deploy`
        3. Observe error in ...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Wrangler config
      description: Relevant sections of your wrangler config (redact any IDs or tokens)
      render: jsonc

  - type: textarea
    id: logs
    attributes:
      label: Error output or logs
      description: Stack trace, wrangler tail output, or console errors
      render: text

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Node 20.x, wrangler 3.x, compatibility_date 2026-01-01"
    validations:
      required: true
