name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve? What workflow does it improve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered or current workarounds

  - type: dropdown
    id: package
    attributes:
      label: Affected package
      description: Which package would this affect?
      options:
        - Consumer SDK
        - Admin SDK
        - Both
        - Documentation
        - CI / Tooling
